name: hascaf
version: 0.1.0.0
github: "dramforever/hascaf"
license: BSD3
author: "dramforever"
maintainer: "dramforever@live.com"
copyright: "2020 dramforever"

extra-source-files:
- README.md

synopsis: Implementation of MiniDecaf in Haskell
category: Compiler

description: Please see the README on GitHub at <https://github.com/dramforever/hascaf#readme>

dependencies:
- base >= 4.7 && < 5
- derive-topdown
- megaparsec
- parser-combinators
- filepath
- text

ghc-options:
- -Wall

default-extensions:
- NumericUnderscores
- OverloadedStrings

library:
  source-dirs: src

executables:
  hascaf:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hascaf
